name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.1
      - name: Install mojo-pkg
        run: curl -fsSL https://raw.githubusercontent.com/Mosaad-M/mojo-pkg/main/scripts/install.sh | bash
      - name: Install dependencies
        run: ~/.mojo/bin/mojo-pkg install
      - name: Run tests
        run: pixi run test-arrow
